# Generated by Django 4.2.29 on 2026-03-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nces_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('locale_type', models.CharField(choices=[('urban', 'Urban'), ('suburban', 'Suburban'), ('town', 'Town'), ('rural', 'Rural')], max_length=10)),
                ('enrollment', models.IntegerField()),
                ('frl_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ell_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['state'], name='districts_d_state_de5918_idx'), models.Index(fields=['locale_type'], name='districts_d_locale__4f002c_idx')],
            },
        ),
    ]
